### PR TITLE
Fix Invalid Namespace Hanging

### PR DESCRIPTION
**Pull request by wilsonge**
If you try and connect to an Invalid namespace you get an error back - but without any handler you end up just hanging (this issue was previously described in more detail here: invisibleroads#84)

I'm not sure whether this belongs in this SocketIO "namespace" or the parent EngineIO - welcome to adjust. Also welcome to adjust on the exception (whether Socket IO specific or another generic Python one)

### CODE REVIEW

**Comment by wilsonge** [comment]
@feus4177 any ideas on this - it's pretty annoying to have to have to extend the class every time just to add this in :(

**Comment by feus4177** [comment]
Hey, sorry about the delay, I was on vacation. It looks like you've got the right idea but could you change it to just `ConnectionError` and add the import statement?

**Comment by wilsonge** [comment]
Apologies for the delay! Implemented the ConnectionError as you requested. Hope you had a nice holiday :)

**Comment by feus4177** [comment]
Alright thanks.

**Pull request merged**
